services:
  - type: web
    name: research-collab-backend
    env: java
    buildCommand: ./mvnw clean install -DskipTests
    startCommand: java -jar target/*.jar
    rootDir: backend-spring
    envVars:
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
      - key: PORT
        value: 8080
